// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuzsycwcjwsuwygsibnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1enN5Y3djandzdXd5Z3NpYm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzI1OTUsImV4cCI6MjA2MzIwODU5NX0.Z0_XaJIiR4BwzDdpgdtdc0i7_UiMCiQclLq48UkCcBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});